# Generated by Django 2.2.4 on 2019-08-11 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("favorite_things_app", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="favoritething",
            name="ranking",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        )
    ]
