# Generated by Django 2.2.4 on 2019-08-11 17:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("favorite_things_app", "0003_auto_20190811_1632")]

    operations = [
        migrations.AlterField(
            model_name="favoritething",
            name="metadata",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        )
    ]
